GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCAyIiwiaWF0IjoxNzM5ODM3ODczLCJleHAiOjE3Mzk4Mzc4ODh9.t4IDAd9RyvSCzc0QA3d5z9khfJMNoOJaCwYjIO4fi4U

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCAyIiwiaWF0IjoxNzM5ODM4MDMxfQ.3fdN2c5WVJGL6nJlD4iOxCtgBYlYxxfuGgb5wzpvqRM"
}

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCAyIiwiaWF0IjoxNzM5ODM4MDMxfQ.3fdN2c5WVJGL6nJlD4iOxCtgBYlYxxfuGgb5wzpvqRM"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "test 2"
}